import { PlayerState, DailyState } from '../hooks/usePlayerState';

/**
 * Encodes bytes to Base64 (pure JS implementation for React Native compatibility)
 */
function bytesToBase64(bytes: Uint8Array): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
  let output = '';

  for (let i = 0; i < bytes.length; i += 3) {
    const byte1 = bytes[i];
    const byte2 = i + 1 < bytes.length ? bytes[i + 1] : 0;
    const byte3 = i + 2 < bytes.length ? bytes[i + 2] : 0;

    const combined = (byte1 << 16) | (byte2 << 8) | byte3;
    const c1 = chars[(combined >> 18) & 63];
    const c2 = chars[(combined >> 12) & 63];
    const c3 = i + 1 < bytes.length ? chars[(combined >> 6) & 63] : '=';
    const c4 = i + 2 < bytes.length ? chars[combined & 63] : '=';

    output += `${c1}${c2}${c3}${c4}`;
  }

  return output;
}

/**
 * Converts UTF-8 text to Base64.
 */
function toBase64Utf8(input: string): string {
  if (typeof TextEncoder !== 'undefined') {
    return bytesToBase64(new TextEncoder().encode(input));
  }

  const escaped = unescape(encodeURIComponent(input));
  const bytes = new Uint8Array(escaped.length);
  for (let i = 0; i < escaped.length; i += 1) {
    bytes[i] = escaped.charCodeAt(i);
  }
  return bytesToBase64(bytes);
}

async function readGithubErrorMessage(res: Response): Promise<string> {
  try {
    const data = await res.json();
    if (data?.message) return data.message;
  } catch {
    // ignored
  }

  try {
    const text = await res.text();
    if (text) return text;
  } catch {
    // ignored
  }

  return `GitHub API request failed with status ${res.status}.`;
}

/**
 * Generates a Markdown log for the day
 */
function generateMarkdownLog(state: PlayerState, day: DailyState): string {
  const routines = [
    { label: 'Breathing', done: day.breathingDone },
    { label: 'Steam', done: day.steamDone },
    { label: 'Sunlight', done: day.sunlightDone },
    { label: 'Walk', done: day.walkDone },
  ];

  return `# ARISE: MISSION LOG — ${day.date}
## Status Window
- **Name**: ${state.name}
- **Level**: ${state.level}
- **Rank**: ${state.rank}
- **Title**: ${state.title}
- **Phase**: ${state.currentPhase}
- **Total Days Completed**: ${state.totalDaysCompleted}
- **Streak**: ${state.streakDays} days

## Daily Objectives
${routines.map(r => `- [${r.done ? 'x' : ' '}] ${r.label}`).join('\n')}
- [${day.waterMl >= day.targetWaterMl ? 'x' : ' '}] Hydration Protocol (${(day.waterMl / 1000).toFixed(1)}L / ${(day.targetWaterMl / 1000).toFixed(1)}L)

## Stats & Health
- **Energy**: ${'★'.repeat(day.energyLevel)}${'☆'.repeat(5 - day.energyLevel)}
- **Symptoms**: ${day.symptomsLog.toUpperCase()}
- **Sleep**: ${day.sleepHours} hours
- **Calories**: ${day.meals.reduce((s, m) => s + m.calories, 0)} kcal
- **Protein**: ${day.meals.reduce((s, m) => s + m.protein, 0)} g

## Nutrition Log
${day.meals.map(m => `- ${m.name}: ${m.calories} kcal, ${m.protein}g P`).join('\n') || '*No meals logged*'}

---
*Generated by ARISE: The System — Level Up Your Life.*
`;
}

export async function pushLogToGithub(state: PlayerState): Promise<{ success: boolean; error?: string; fileUrl?: string }> {
  const config = state.githubConfig;
  if (!config || !config.token || !config.repo || !config.owner) {
    return { success: false, error: 'GitHub not configured' };
  }

  const { token, repo, owner } = config;
  const day = state.today;
  const fileName = `logs/mission_log_${day.date}.md`;
  const content = generateMarkdownLog(state, day);
  const base64Content = toBase64Utf8(content);

  try {
    // 1. Check if file exists to get SHA (needed for updates)
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${fileName}`;
    let sha: string | undefined;

    const checkRes = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    });

    if (checkRes.ok) {
      const data = await checkRes.json();
      sha = data.sha;
    } else if (checkRes.status !== 404) {
      const message = await readGithubErrorMessage(checkRes);
      return { success: false, error: message };
    }

    // 2. Put (Create or Update) the file
    const putRes = await fetch(url, {
      method: 'PUT',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        message: `System Log: Mission Complete — ${day.date}`,
        content: base64Content,
        sha: sha, // Include SHA if we're updating
      }),
    });

    if (!putRes.ok) {
      const message = await readGithubErrorMessage(putRes);
      return { success: false, error: message };
    }

    const data = await putRes.json();
    const fileUrl = data?.content?.html_url || data?.content?.download_url;
    return { success: true, fileUrl };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown network error';
    return { success: false, error: message };
  }
}
